### PR TITLE
Upgrade to Python3 for Kodi Matrix (v19.0)

### PR DESCRIPTION
**Pull request by stdedos**
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

### CODE REVIEW

**Comment by stdedos** [comment]
Should be ready now; I have tested it and it gives even a little bit more functionality.

Kindly respond, or I will have to turn to Kodi Maintainers

**Comment by realgam3** [comment]
It could break the kodi <= v18 plugin,
I need it to be backward compatible.

It should be tested also on android before committed.

**Comment by stdedos** [comment]
> It could break the kodi <= v18 plugin,
> I need it to be backward compatible.

That is beyond the scope I am interested to commit to.
Bear in mind that all v18 addons (Leia) need to be both python2 and python3 compatible!

Given the extend of 2to3 changes (automatic or otherwise), I don't think that's feasible.
You can branch off your current master to `compatibility/leia` if you want, and then commit this to master.

I don't know how the packaging works in that case though.

> It should be tested also on android before committed.

My testing ground _is_ Android 😉

**Comment by realgam3** [comment]
> Given the extend of 2to3 changes (automatic or otherwise), I don't think that's feasible.

I know it is I have the BSPlayer Library running on my server with backward compatibility,
I will not be able to approve you pull request without it,
I will mention you after fixing the issue. (and you could open just an issue)

**Comment by stdedos** [comment]
Okay, looking forward to see what changes come.

When that's all done, let's see if you'd consider my other enhancements / improvements.

**Comment by realgam3** [comment]
> Okay, looking forward to see what changes come.
> 
> When that's all done, let's see if you'd consider my other enhancements / improvements.

NP I will check with Kodi maintainers what they suggest maybe we will take your approach. :)

**Comment by realgam3** [comment]
Can you add python3 as dependency?
I'm not sure if its possible to add minimal version

**Comment by stdedos** [comment]
> Can you add python3 as dependency?

Where exactly? 😕 addons.xml already contains it

**Comment by stdedos** [comment]
Friendly ping @realgam3

**Comment by NoahKr** [comment]
Any update on this? I would really like to use it with kodi 19

**Comment by stdedos** [comment]
No 😕 

And, unfortunately, on my installation, there is some memory corruption - you may need to terminate Kodi and restart it to use it.

I am mostly certain it's Kodi's bug - but I cannot agree with Kodi maintainers to take a look at it.

**Comment by NoahKr** [comment]
That's unfortunate. Thanks for trying and replying anyway

**Pull request closed without merging**
